nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-bump.cjs
    spec: "https://github.com/cometkim/yarn-plugin-bump/releases/download/v0.0.8/plugin-bump.js"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
